import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/providers/modal-provider";
import { Toaster } from "react-hot-toast";
import { ToasterProvider } from "@/providers/toast-provider";

=======
>>>>>>> 4e60d2240aac6c2620da5470395680eb6180e3f2

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <ModalProvider />
        {children}</body>
    </html>
    </ClerkProvider>
=======
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
>>>>>>> 4e60d2240aac6c2620da5470395680eb6180e3f2
  );
}
